cmd_/home/ams/linux-kernel/test/kthread/./src/call_rcu/api.o := gcc -Wp,-MD,/home/ams/linux-kernel/test/kthread/./src/call_rcu/.api.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/include  -I/usr/src/linux-headers-3.13.0-36-generic/arch/x86/include -Iarch/x86/include/generated  -Iinclude -I/usr/src/linux-headers-3.13.0-36-generic/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/usr/src/linux-headers-3.13.0-36-generic/include/uapi -Iinclude/generated/uapi -include /usr/src/linux-headers-3.13.0-36-generic/include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m64 -mno-mmx -mno-sse -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -fstack-protector -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=1024 -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO -I/home/ams/linux-kernel/test/kthread/include -DSTATIC_INIT_THREAD  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(api)"  -D"KBUILD_MODNAME=KBUILD_STR(callrcu)" -c -o /home/ams/linux-kernel/test/kthread/./src/call_rcu/.tmp_api.o /home/ams/linux-kernel/test/kthread/./src/call_rcu/api.c

source_/home/ams/linux-kernel/test/kthread/./src/call_rcu/api.o := /home/ams/linux-kernel/test/kthread/./src/call_rcu/api.c

deps_/home/ams/linux-kernel/test/kthread/./src/call_rcu/api.o := \

/home/ams/linux-kernel/test/kthread/./src/call_rcu/api.o: $(deps_/home/ams/linux-kernel/test/kthread/./src/call_rcu/api.o)

$(deps_/home/ams/linux-kernel/test/kthread/./src/call_rcu/api.o):
